export const LIST_DATA = 'LIST_DATA' // 计算器
export const LIST_TABLE = 'LIST_TABLE' // 计算器返回值
export const TREE_DATA = 'TREE_DATA'   // 字典 tree
export const TREE_SON = 'TREE_SON'    // 字典项
export const TREE_FORMULA = 'TREE_FORMULA' // 公式 tree
export const TREE_ID = 'TREE_ID' // 树ID
export const TABLE_VALUE = 'TABLE_VALUE' // 表格数据
export const MODIFY_MODEL = 'MODIFY_MODEL' // 修改字典
export const TAX_MODEL = 'TAX_MODEL' // 税种字典项
export const TAX_VALUES = 'TAX_VALUES' // 传税种用来接收返回的字典名称
export const TAX_NAME = 'TAX_NAME' // 税种的name
export const DICTIONARY_ID = 'DICTIONARY_ID' // 字典项目id
export const ITEM_NAME = 'ITEM_NAME' // 字典项的 集合
export const ADD_FORMULA = 'ADD_FORMULA' // 新增公式
export const TREE_FORMULA_ID = 'TREE_FORMULA_ID' // 公式id
export const FORMULA_NAMES = 'FORMULA_NAMES' // 传公式id返回字典名称
export const FORMULA_MODEL = 'FORMULA_MODEL' // 修改公式
